[package]
name = "coffee-2d"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
coffee = { version = "0.4", features = ["opengl"] }
natura = {path= "../../natura" }